
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FOS.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_IZConsumers
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Tbl_IZConsumers()
    {

        this.Tbl_IZPayments = new HashSet<Tbl_IZPayments>();

        this.TBl_IZSocietyCharges = new HashSet<TBl_IZSocietyCharges>();

    }


    public int ID { get; set; }

    public string RefNo { get; set; }

    public string PlotNo { get; set; }

    public string MeterType { get; set; }

    public string MeterNo { get; set; }

    public string Phase { get; set; }

    public string ConnectionType { get; set; }

    public Nullable<System.DateTime> ConnectionDate { get; set; }

    public string OwnerName { get; set; }

    public string Address { get; set; }

    public string CNIC { get; set; }

    public string PhoneNo { get; set; }

    public Nullable<bool> Status { get; set; }

    public string PTV { get; set; }

    public Nullable<bool> Filer { get; set; }

    public string NTN { get; set; }

    public string CoOwnerName { get; set; }

    public string CoOwnerCNIC { get; set; }

    public Nullable<int> CoOwnerContact { get; set; }

    public Nullable<decimal> Latitude { get; set; }

    public Nullable<decimal> Longitude { get; set; }

    public string Location { get; set; }

    public Nullable<int> BlockID { get; set; }

    public string ConsumerID { get; set; }

    public Nullable<int> ConsumerIDFinal { get; set; }

    public string AccNO { get; set; }

    public string SubAcco { get; set; }

    public string MemberNO { get; set; }

    public string SubHead { get; set; }

    public string CellNo { get; set; }

    public string ChallanNo { get; set; }

    public Nullable<System.DateTime> ChallanDate { get; set; }

    public string MeterMonth { get; set; }

    public string currentReading { get; set; }

    public Nullable<double> MF { get; set; }

    public Nullable<int> TeriffID { get; set; }

    public string Teriff { get; set; }

    public string BlockName { get; set; }

    public Nullable<int> MeterStatusID { get; set; }



    public virtual Tbl_IZMeterStatus Tbl_IZMeterStatus { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tbl_IZPayments> Tbl_IZPayments { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TBl_IZSocietyCharges> TBl_IZSocietyCharges { get; set; }

}

}
