
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FOS.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class TBl_IZSocietyCharges
{

    public int ID { get; set; }

    public Nullable<int> ConsumerID { get; set; }

    public string ConsumerRefNo { get; set; }

    public string meterNo { get; set; }

    public string StreetLight { get; set; }

    public string Garbage { get; set; }

    public string Water { get; set; }

    public string Sew { get; set; }

    public string PTVFee { get; set; }

    public string OtherCharges { get; set; }

    public string Maintenace { get; set; }



    public virtual Tbl_IZConsumers Tbl_IZConsumers { get; set; }

}

}
