
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FOS.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_IZPayments
{

    public int ID { get; set; }

    public Nullable<int> ConsumerID { get; set; }

    public string PaymentType { get; set; }

    public string TransanctionType { get; set; }

    public Nullable<int> BankID { get; set; }

    public Nullable<System.DateTime> PaymentDate { get; set; }

    public Nullable<int> MonthID { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> UpdateOn { get; set; }

    public Nullable<int> UpdateBy { get; set; }

    public string Amount { get; set; }

    public string CSV { get; set; }

    public string MF { get; set; }



    public virtual Tbl_IZBanks Tbl_IZBanks { get; set; }

    public virtual Tbl_IZBillingPeriod Tbl_IZBillingPeriod { get; set; }

    public virtual Tbl_IZConsumers Tbl_IZConsumers { get; set; }

}

}
