//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BillingBills
    {
        public int ID { get; set; }
        public Nullable<int> BillID { get; set; }
        public Nullable<int> ConsumerID { get; set; }
        public string ConsumerName { get; set; }
        public Nullable<System.DateTime> BillingMonth { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> AmountDue { get; set; }
        public Nullable<int> AmountAfterDueDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> BiilingPeriod { get; set; }
        public Nullable<bool> BillingPeriodStatus { get; set; }
        public string BillingPeriodTitle { get; set; }
    }
}
