//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ReceiptBills
    {
        public int ID { get; set; }
        public Nullable<int> BillID { get; set; }
        public Nullable<int> ReceiveAmount { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<System.DateTime> BillingMonth { get; set; }
        public Nullable<int> ConsumerNo { get; set; }
        public string ConsumerName { get; set; }
        public Nullable<System.DateTime> BillIssueDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> AmountDue { get; set; }
        public Nullable<int> AmountAfterDueDate { get; set; }
        public string BillStatus { get; set; }
        public string BillingPeriodTitle { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
