
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FOS.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_IZTeriffCode
{

    public int ID { get; set; }

    public string teriffCode { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<System.DateTime> CreatedAt { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedAt { get; set; }

    public Nullable<int> Updateby { get; set; }

}

}
