
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FOS.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_IZBillingParameter
{

    public int ParaID { get; set; }

    public string Name { get; set; }

    public string Domestic { get; set; }

    public string DomesticTemp { get; set; }

    public string Commercial { get; set; }

    public string Soceity { get; set; }

    public string TeleCommunication { get; set; }

    public string FPA { get; set; }

    public Nullable<int> MonthID { get; set; }

    public Nullable<System.DateTime> ReadingStart { get; set; }

    public Nullable<System.DateTime> BillIssueDate { get; set; }

    public Nullable<System.DateTime> BillDueDate { get; set; }



    public virtual Tbl_IZBillingPeriod Tbl_IZBillingPeriod { get; set; }

}

}
